---
model: 'Transformer'
dst_vocab: '/mnt/lustre/xushuang2/syzhou/tensor2tensor/SEAME/seame_s2s/words_s2s.txt'
dst_vocab_size: 3205
#### hidden_units: 512
hidden_units: 1024
scale_embedding: True
tie_embedding_and_softmax: True
attention_dropout_rate: 0.0
#### residual_dropout_rate: 0.1
residual_dropout_rate: 0.3
num_blocks: 6
#### num_heads: 8
num_heads: 16
ff_activation: 'glu'
model_dir: './exp/log_dir_left3_sub3_lr1.0_char_big_dim80_seame'
bucket_min: 50
bucket_max: 10000
bucket_step: 10
min_count_in_bucket: 20
is_attention_smoothing: False
train:
    num_gpus: 8
    tokens_per_batch: 30000
    src_path: '/mnt/lustre/xushuang2/syzhou/tensor2tensor/SEAME/seame_s2s/data/train_dim80/feats.scp.left3_sub3'
    dst_path: '/mnt/lustre/xushuang2/syzhou/tensor2tensor/SEAME/seame_s2s/data/train_dim80/text.char'
    max_length: 1500
    num_epochs: 90
    num_steps: 300000
    save_freq: 200
    show_freq: 1
    summary_freq: 100
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 1
    warmup_steps: 12000
    label_smoothing: 0.1
    toleration: 10
    eval_on_dev: False
    input_dim: 320
    var_filter: ''
dev:
    batch_size: 256
    src_path:
    ref_path:
    output_path:

test:
    batch_size: 50
    tokens_per_batch: 7000
    max_target_length: 200 
    lp_alpha: 0.6 
    beam_size: 13
    num_gpus: 8

    set1:
        src_path: '/mnt/lustre/xushuang2/syzhou/tensor2tensor/SEAME/seame_s2s/data/dev_man_dim80/feats.scp.left3_sub3'
        ref_path: ''
        output_path: './exp/log_dir_left3_sub3_lr1.0_char_big_dim80_seame/decode_dev_man/decoder.txt'
        cmd:

    set2:
        src_path: '/mnt/lustre/xushuang2/syzhou/tensor2tensor/SEAME/seame_s2s/data/dev_sge_dim80/feats.scp.left3_sub3'
        ref_path: ''
        output_path: './exp/log_dir_left3_sub3_lr1.0_char_big_dim80_seame/decode_dev_sge/decoder.txt'
        cmd:

